import { NextPage } from "next"

const TermsOfUse: NextPage = () => {
    return (
        <>
            <h1 id="adao-staking-portal-terms-of-use">ADAO STAKING PORTAL - TERMS OF USE</h1>
            <p>All decentralized applications (dApps) operating on the blockchain involve various risks to participants and the ADAO Staking Portal is no different. Such risks include, but not limited to potential losses either due to user error, unidentified vulnerabilities or weaknesses in the integrity of the software code comprising the protocol and open-source smart contracts upon which the protocol relies to function properly, among other known and unknown risks. Users must understand, consider and accept all risks involved before engaging with the protocol. Any loss involved in the use of dApps is unrecoverable by the user and without recourse against any third party. Users accessing and engaging with the ADAO Staking Portal are solely responsible for any and all losses, financial or otherwise, they may potentially incur, and fully and unconditionally agree to all of the terms and conditions contained herein.</p>
            <p><strong>THE ADAO STAKING PORTAL PROTOCOL IS PROVIDED “AS IS”, AT YOUR OWN RISK, AND WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED.</strong></p>
            <p>The ADAO Staking Portal operates primarily via self-executing smart contracts deployed on the Cardano blockchain.</p>
            <p>Upgrades and modifications to the ADAO Staking Portal protocol are managed by ADAO’s decentralized community of DAO members holding the ADAO governance token. This form of decentralized protocol maintenance and management is accomplished by a governance mechanism which allows for ADAO governance token holders to submit and vote on proposals for upgrades and changes to the ADAO Staking Portal protocol. No single developer or other person or entity involved in creating or maintaining the ADAO Staking Portal protocol on behalf of the community of participating ADAO governance token holders will be liable for any claims or damages whatsoever associated with any and all use, inability to use, and/or interaction with the ADAO Staking Portal protocol or its community of users, including without limitation any direct, indirect, incidental, special, exemplary, punitive or consequential damages, or loss of profits, cryptocurrencies, tokens, or anything else of value. By proceeding to engage with the ADAO Staking Portal you hereby agree to waive and release any and all third parties from any and all liability arising from your use of the protocol to the greatest extent enforceable under the law.</p>
            <h2 id="restrictions-of-use-and-compliance-obligations-">Restrictions of Use and Compliance Obligations:</h2>
            <p>Due to the decentralized nature of the ADAO Staking Portal, users are responsible for ensuring their own compliance with all laws and regulations governing participation in certain activities related to digital assets, such as those the ADAO Staking Portal enables, which may vary widely according to each user’s specific jurisdiction. By accessing or using the ADAO Staking Portal, you manifest your acceptance of these terms and expressly represent and warrant that you will comply with all laws, regulations, and other requirements applicable to you according to your particular jurisdiction of residency or citizenship.</p>
            <p>Use of the ADAO Staking Portal protocol by users located in or resident of jurisdictions which prohibit or impose limitations upon the activities enabled by the protocol are strictly prohibited from accessing or using the protocol in any manner that does not comport with applicable legal and regulatory requirements, and you otherwise agree you will not utilize the protocol to engage in any activities related to cryptocurrency or other digital assets which are prohibited by in your place of domicile, residency, or citizenship, which are subject to change from time to time without notice. It is the sole responsibility of each user of ADAO Staking Portal, and any other decentralized or autonomous blockchain protocol to understand the requirements that apply to their jurisdiction.</p>
            <h1 id="for-the-avoidance-of-doubt-users-of-the-protocol-are-solely-responsible-for-understanding-and-ensuring-their-own-compliance-with-any-and-all-legal-and-regulatory-requirements-specific-to-them-">FOR THE AVOIDANCE OF DOUBT, USERS OF THE PROTOCOL ARE SOLELY RESPONSIBLE FOR UNDERSTANDING AND ENSURING THEIR OWN COMPLIANCE WITH ANY AND ALL LEGAL AND REGULATORY REQUIREMENTS SPECIFIC TO THEM.</h1>
            <p>By accessing and using, or attempting to access or use, the ADAO Staking Portal protocol, you represent and warrant the following:</p>
            <ol>
                <li>You are not a citizen, resident and/or domiciliary of the United States or its territories;<ol>
                    <li>You are not accessing or using the ADAO Staking Portal, or attempting to do so, from a country embargoed or restricted by the United States Treasury Department<em>’</em>s Office of Foreign Asset Control (OFAC) or the Swiss State Secretariat for Economic Affairs (SECO), which is subject to change, however currently includes the following prohibited jurisdictions and territories: Belarus, Burundi, Central African Republic, Congo, North Korea (DPRK), Guinea, Guinea-Bissau, Iran, Iraq, Lebanon, Libya, Mali, Myanmar(Burma), Republic of South Sudan, Somalia, Sudan, Syria, Ukraine, Venezuela, Yemen, and Zimbabwe. Pursuant to applicable laws and regulations, the ADAO governance token holders maintain the right to elect which markets, states, regions, jurisdictions and territories from which it permits access to or use of the protocol, and may collectively decide to restrict or deny the use of the protocol, websites related to the protocol, content or any part or combination thereof, at its sole discretion; and</li>
                    <li>You will hold harmless and release from liability without limitation ADAO and any and all third parties for any and all legal claims for any losses or damages you may incur that arise from voluntarily accessing and engaging with the ADAO Staking Portal.</li>
                </ol>
                </li>
            </ol>
            <h2 id="terms-of-use">Terms of Use</h2>
            <p>You represent and warrant that you have full right and authority to use the ADAO Staking Portal protocol and to be bound by these Terms of Use. You agree that you will comply fully with these Terms and all applicable domestic and international laws, regulations, statutes, ordinances that govern your use of the software. Without limiting the foregoing and in recognition of the global nature of the decentralized Cardano blockchain network, you agree to comply with all local and international rules regarding online conduct. You also agree to comply with all applicable laws affecting the transmission of content or the privacy of persons. When using the software and its related properties, you may not, nor may you assist other parties to pursuit or engage in unlawful or abusive uses, or any types of activities which contradict the purpose of the software protocol to other users, or which may be deemed to do so (<em>“</em>Restricted Uses<em>”</em>). For Clarity and reference, Restricted Uses include, but are not limited to, these types of activities as detailed herein, as we may amend from time to time in our sole discretion (thus, not to be regarded as an exhaustive list):</p>
            <ul>
                <li>Unlawful Activities, such as activities which:</li>
                <li>Violate any applicable law, rule or regulation; or</li>
                <li>publish, distribute or disseminate any unlawful material or information;</li>
                <li>Undermining or Abusive Activities, such as activities which:</li>
                <li>Take any action that imposes an unreasonable or disproportionately large load on our infrastructure, or detrimentally interfere with, intercept, or expropriate any system, data, or information;</li>
                <li>Institute, assist or become involved in any type of attack (deliberate or other), including distribution of a virus, attacks upon the Content, the ADAO Staking Portal software that prevent access to or use of any of the above, other attempts to disrupt any of the above, gain unauthorized access to any of the above, or disrupt any other person<em>’</em>s use or enjoyment of any of the above;<ul>
                    <li>Enter or make an attempt to enter the Site and Content (including by accessing linked platforms, networks or systems) unauthorized, including by password mining and/or by using other users information;</li>
                </ul>
                </li>
                <li>Design or assist in designing cheats, exploits, automation software, bots, hacks, modes or any other unauthorized third-party software to modify or interfere with the software code or its ability to function properly;</li>
                <li>Attempt to disable or circumvent any security or access control mechanism of the software and/or its underlying smart contracts;</li>
                <li>Use any unauthorized third-party software that accesses, intercepts, &#39;mines&#39;, or otherwise collects information from or through the software or sites associated with the software or related web properties;<ul>
                    <li>Copy, modify, or create derivative works of the ADAO Staking Portal unless permitted in accordance with these Terms of Use and the license grants reflected herein.</li>
                </ul>
                </li>
                <li>Activities Infringing Intellectual Property, such as activities which:</li>
                <li>Reverse engineer, decompile, disassemble, decipher or otherwise attempt to derive the source code for any underlying proprietary (non-open source) components of software or other intellectual property used to provide the Content, or to obtain any information from the Content using any method unless you have received prior written approval; or</li>
                <li>Infringe the intellectual property rights, privacy rights, or moral rights of any third party or ADAO;</li>
                <li>Unfair or Abusive Transacting, such as activities which:</li>
                <li>Create or enter a fictitious transaction or a transaction with fictitious elements of any kind;</li>
                <li>Exploit, disrupt or manipulate, or attempt to exploit, disrupt or manipulate the Site or the use of the Content, in a manner designed to create transaction conditions which are not available to other users in any manner whatsoever;<ul>
                    <li>Utilizes or applies technological abilities or foreknowledge not exploited or available to other Users, to perform (including off Site) transactions parallel to those performed by Users on the Site, and/or create unequal terms among Users regarding the use of Content on the Site, or influence the terms of transactions on the blockchain (including activities commonly referred to as Front-Running) and/or create an unfair or abusive advantage over other Users;<ul>
                        <li>Violation of any of these Restricted Uses may be cause for the taking of legal actions on the part of ADAO or its assigns according to the law, in addition to any right and remedies set forth hereunder or under any applicable law. Without derogating from the above, by accepting these Terms, you acknowledge that ADAO makes no representation or warranty regarding its ability, nor assumes any liability, to detect, limit or prevent any Restricted Use.</li>
                    </ul>
                    </li>
                </ul>
                </li>
            </ul>
            <p><strong>Limitation or Termination of Access and Services</strong></p>
            <h1 id="adao-staking-portal-may-in-its-sole-discretion-refuse-to-make-the-content-available-to-any-person-or-entity-we-may-without-notice-and-in-our-sole-discretion-terminate-your-right-to-use-the-content-or-any-portion-thereof-and-block-or-prevent-your-future-access-to-and-use-of-the-content-or-any-portion-thereof-we-may-at-any-time-and-for-any-reason-and-in-our-sole-discretion-discontinue-the-content-in-its-entirety-or-any-part-hereof-without-prior-notice-and-or-liability-of-any-kind-">ADAO STAKING PORTAL MAY, IN ITS SOLE DISCRETION, REFUSE TO MAKE THE CONTENT AVAILABLE TO ANY PERSON OR ENTITY. WE MAY, WITHOUT NOTICE AND IN OUR SOLE DISCRETION, TERMINATE YOUR RIGHT TO USE THE CONTENT OR ANY PORTION THEREOF, AND BLOCK OR PREVENT YOUR FUTURE ACCESS TO AND USE OF THE CONTENT OR ANY PORTION THEREOF. WE MAY, AT ANY TIME AND FOR ANY REASON AND IN OUR SOLE DISCRETION, DISCONTINUE THE CONTENT IN ITS ENTIRETY, OR ANY PART HEREOF, WITHOUT PRIOR NOTICE AND/OR LIABILITY OF ANY KIND.</h1>
            <p>Subject to your agreement and compliance with these Terms, you are hereby granted with a personal, revocable, non-transferable and non-exclusive right to use the Content. Use of the Content shall be solely for your own, private purposes and for no other purpose whatsoever. You hereby acknowledge that your right to use the Content is limited by these Terms, and, if you violate or if, at any point, you do not agree to any of these Terms, your right to use the software shall immediately terminate, and you shall immediately refrain from using the software made available pursuant to this license. Without derogating from the generality of the foregoing, any use of the Content that violates these Terms is strictly prohibited and can, at ADAO’s sole discretion, result in the immediate revocation of your limited rights granted by these Terms. Without limiting any other remedy, ADAO may limit, suspend, revoke, terminate, modify, or delete your access to the software and related web properties and/or sites at its sole discretion without prior notice or liability, if you are, or if ADAO suspects (in its sole discretion) that you are failing to comply with these Terms or for any actual or suspected Restricted Use of the software comprising the ADAO Staking Portal. Any of such actions, including the termination of your rights to use the software, may be applied by ADAO permanently or temporarily. In such an event, ADAO may terminate your access to whatever extent possible (however without affecting your Wallet, which remains exclusively yours, subject to any applicable third-party terms of use or law).</p>
            <p>## </p>
            <h2 id="intellectual-property">Intellectual Property</h2>
            <ul>
                <li>The Content and all of the content that appears in the Site, including without limitation, the use of the Site’s name, software, web technologies, source code, concepts, artwork, photos, animations, sounds, methods of operation, moral rights, documentation, and virtual items, other than open-source material, such as underlying smart contract code, is the exclusive property of ADAO, or is being used with permission from its licensors (as applicable) shall retain all rights, title and interest in the proprietary elements of the ADAO Staking Portal software, and all intellectual property rights relating thereto, including without limitations all copyright, patent, trademarks, logos, design rights and any other proprietary rights connected with the content comprising the software. Notwithstanding any provision to the contrary herein, you agree that you have no right or title in or to the software and/or to any content that appears in connection with the software. ADAO’s name and logo, and any other trademarks included in the Content and/or appear on the Site, are trademarks of ADAO and/or its partners, affiliates or licensing partners, as may be applicable.</li>
                <li>All third-party product names that may legitimately appear in the Site are trademarks of their respective owners. No transfer or grant of any rights under any names, marks or logos is made or is to be implied by any provision of these Terms or by anything on the Site, and all rights in such names, marks or logos is reserved to ADAO Staking Portal or their respective owners, as applicable.</li>
            </ul>
            <h2 id="third-party-content">Third Party Content</h2>
            <ul>
                <li>To the extent that the software or related web properties and/or sites contain links or any other information to third party websites, tokens or services, ADAO does not control the availability and content of those websites, tokens and services. Any concerns regarding any such third-party websites, tokens and/or service, or any link thereto, should be directed to such particular website and/or services provider. ADAO makes no representation or warranty regarding any content, goods, tokens and/or services provided by any third party, even if linked to through the site or the service.</li>
                <li>The linked sites and tokens are not under the control of ADAO and may collect data or solicit personal information from you. ADAO is not responsible for their content, business practices or privacy policies, or for the collection, use or disclosure of any information those sites may collect. you agree that the services may feature advertisements from third parties. ADAO is not responsible for the actions of third parties who advertise on the site. Your interactions with advertisers or entities that issued the tokens are agreements between you and them with ADAO having no responsibility for such interactions.</li>
            </ul>
            <h2 id="risk-statement-representations-and-warranties">Risk Statement, Representations and Warranties</h2>
            <p>The ADAO Staking Portal provides a permissionless access point to a set of open-source smart contracts, consisting in whole or in part open-source software code. As a general matter, Users should be aware of the following prior to utilizing decentralized applications such as the ADAO Staking Portal:</p>
            <ul>
                <li>By using the ADAO Staking portal or related software, you acknowledge the inherent risks associated with decentralized and/or cryptographic systems and ecosystems; and warrant that you have an understanding of the usage and intricacies of native cryptographic tokens and blockchain-based software systems. You understand that blockchain technologies and associated digital assets, currencies or tokens are associated with volatile market conditions due to many factors including but not limited to adoption, speculation, technology, security risks and a wide range of other known and unknown drivers.</li>
                <li>You further acknowledge that the cost of transacting on such technologies (where applicable) is variable and may increase at any time causing impact to any activities taking place on the relevant blockchain (such as Cardano). You acknowledge these risks and represent that ADAO cannot be held liable for such fluctuations or increased costs in some or all of the fees and/or transaction costs incurred in connection with your use of the ADAO Staking Portal whenever applicable. ADAO cannot be held liable for any losses or damages of ADA, ADAO governance tokens, or any other digital asset, resulting from the use of services of any third-party provider.</li>
                <li>The ADAO Staking Portal could be impacted by one or more regulatory inquiries or regulatory action, which could impede or limit the ability of ADAO or the blockchain developer community at large to continue to develop, or which could impede or limit your ability to access or use the software or the blockchain. ADAO endeavors to comply with all applicable laws, such as all legal requests for information, and reserve the right to provide information, including Project Information, to law enforcement personnel and other third parties to answer inquiries, to respond to legal process, to respond to the order of a court of competent jurisdiction and those exercising the court <em>’</em> s authority and to protect ADAO Staking Portal Users.</li>
                <li>You are solely responsible for complying with all laws and regulations that apply to you. You agree that ADAO is not responsible for determining whether or which laws may apply to you, including with respect to tax or securities regulations. You are solely responsible for reporting and paying any taxes arising from your use of the ADAO Staking Portal as required by your tax jurisdiction.</li>
                <li>ADAO does not advise on risks associated with the use of applications such as the ADAO Staking Portal. You are solely responsible for doing your own research prior to interacting with the ADAO Staking Portal, and that in no case shall ADAO be responsible for any information, commentary, or advice, whether express or implied, that may influence users’ behavior in connection with the manner in which they interact with the ADAO or the ADAO Staking Portal.</li>
                <li>ADAO does not own, control or maintain, and therefore cannot ensure the integrity of certain elements of the protocol outside its control, such as the underlying blockchain or other third-party software protocols which govern the operations supported by the ADAO Staking Portal;</li>
            </ul>
            <h2 id="ownership-of-tokens-and-other-digital-assets">Ownership of Tokens and Other Digital Assets</h2>
            <p>You hereby warrant and represent that any Tokens used by you in connection with the Content are either owned by you or that you are validly authorized to carry out conversions, and to take (or refrain from taking) any other actions which you perform while using the Content, using such Tokens.</p>
            <h2 id="indemnification">Indemnification</h2>
            <p>You agree to indemnify, defend and hold ADAO, its decentralized members, software users and licensees, affiliates and service providers, including its individual developers, and as applicable, each of their respective officers, directors, agents, employees, and representatives, harmless from any claim (including, but without limitation, third party claims) or demand (including attorneys <em>’</em> fees and costs and any fines, fees or penalties imposed by any regulatory authority) arising out of or any way connected to your use or misuse of the ADAO Staking Portal protocol of any kind whatsoever related to: (i) your breach of these Terms, (ii) your use or access of the Site and/or Content, or (iii) your violation of any law, rule, or regulation, or the rights of any third party.</p>
            <h1 id="warranty-disclaimer">WARRANTY DISCLAIMER</h1>
            <p>BY USING OR ACCESSING THE ADAO STAKING PORTAL PROTOCOL, YOU ACKNOWLEDGE, UNDERSTAND, AND AGREE TO THE FOLLOWING:</p>
            <p>BLOCKCHAIN APPLICATIONS AND PROTOCOLS ARE GENERALLY STILL IN AN EARLY DEVELOPMENT STAGE AND THEREFORE OF EXPERIMENTAL NATURE. YOU THEREFORE UNDERSTAND THAT THE CONTENTS ARE PROVIDED TO YOU <em>‘</em> AS IS <em>’</em> AND WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND EITHER EXPRESSED OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, EACH OF ADAO STAKING PORTAL AND/OR ADAO STAKING PORTAL PARTIES DISCLAIMS ALL WARRANTIES, EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF ANY KIND IN CONNECTION WITH THE TOKENS, THE CONTENT, NON-INFRINGEMENT, AND FITNESS FOR ANY PARTICULAR PURPOSE, USEFULNESS, AUTHORITY, ACCURACY, COMPLETENESS AND/OR TIMELINESS.</p>
            <p>ADAO MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE CONTENT OF ANY SITES LINKED TO THE CONTENTS, OF ANY THIRD-PARTY MATERIALS OR THE UNDERLYING SOFTWARE PROTOCOL (THE SOFTWARE) THAT GOVERNS THE CONTENT AND THE ADAO STAKING PORTAL NETWORK. WITHOUT LIMITING THE FOREGOING, NEITHER ADAO STAKING PORTAL NOR ITS AFFILIATES OR SUBSIDIARIES, OR ANY OF ITS OR THEIR DIRECTORS, EMPLOYEES, AGENTS, ATTORNEYS, THIRD-PARTY CONTENT PROVIDERS, DISTRIBUTORS, JOINT-VENTURES, LICENSEES OR LICENSORS (COLLECTIVELY, “ADAO”) REPRESENT OR WARRANT THAT THE SITE AND THE CONTENT WILL BE UNINTERRUPTED, ERROR-FREE, BUG-FREE OR FREE FROM VIRUSES OR OTHER HARMFUL COMPONENTS.</p>
            <p>USE OF THE SITE AND THE CONTENT IS ENTIRELY VOLUNTARY AND AT YOUR SOLE RISK. ADDITIONALLY, IN NO EVENT SHALL ADAO BE LIABLE FOR ANY UNAUTHORIZED ACCESS TO OR USE OF THIRD-PARTY MATERIALS, SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN. YOU ACKNOWLEDGE AND AGREE THAT, TO THE FULLEST EXTENT PERMITTED BY ANY APPLICABLE LAW, THE DISCLAIMERS CONTAINED HEREIN SHALL APPLY TO ANY AND ALL DAMAGES OR INJURIES WHATSOEVER CAUSED BY OR RELATED TO THE USE OF, OR INABILITY TO USE, THE CONTENTS, UNDER ANY CAUSE OR ACTION WHATSOEVER OF ANY JURISDICTION, INCLUDING, WITHOUT LIMITATION, ACTIONS FOR BREACH OF WARRANTY, BREACH OF CONTRACT OR TORT (INCLUDING NEGLIGENCE).</p>
            <p>UNDER NO CIRCUMSTANCES WHATSOEVER WILL ADAO AND/OR ANY PARTIES RELATED TO ADAO OR THE ADAO STAKING PORTAL SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, BE RESPONSIBLE OR LIABLE TO YOU OR TO ANY OTHER ENTITY FOR ANY COMPENSATORY, INDIRECT, INCIDENTAL, CONSEQUENTIAL (INCLUDING FOR LOSS OF PROFITS, LOST BUSINESS OPPORTUNITIES, LOSS OF GOODWILL OR DATA DESTRUCTION OR IMPAIRMENT) SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES THAT RESULT FROM OR RELATE IN ANY MANNER WHATSOEVER TO YOUR USE OF OR INABILITY TO USE THE CONTENTS. IF YOU ARE DISSATISFIED WITH THE CONTENTS, OR WITH THESE TERMS, OR YOU HAVE ANY DISPUTE WITH ADAO AND/OR ANY PARTIES RELATED TO ADAO, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE CONTENTS. YOU FURTHER SPECIFICALLY ACKNOWLEDGE THAT NEITHER ADAO STAKING PORTAL NOR ANY ADAO STAKING PORTAL PARTIES ARE LIABLE, AND YOU AGREE NOT TO SEEK TO HOLD ADAO STAKING PORTAL AND/OR ADAO STAKING PORTAL PARTIES LIABLE, FOR THE CONDUCT OF THIRD PARTIES, INCLUDING OTHER USERS OF THE CONTENTS, ISSUERS OF TOKENS AND OPERATORS OF EXTERNAL SITES, AND THAT THE RISK REGARDING THE FOREGOING RESTS ENTIRELY WITH YOU.</p>
            <p>ADAO, ADAO &apos; S DECENTRALIZED MEMBERS AND/OR ITS DEVELOPERS, AFFILITATES, CONTRACTORS, AGENTS, PARTNERS, USERS, OR ANY OTHER THIRD PARTY SHALL NOT BE DEEMED TO BE IN BREACH OF THESE TERMS, NOR SHALL ANY LIABILITY INCUR DUE TO A DELAY OR FAILURE IN PERFORMANCE CAUSED BY FORCE MAJEURE. FORCE MAJEURE REFERRERS TO CIRCUMSTANCES BEYOND OUR REASONABLE CONTROL, INCLUDING BUT NOT LIMITED TO ACTS OF GOD, FIRE, FLOOD, WAR, TERRORISM, EMBARGO, ACCIDENT, LABOR DISPUTES, OR SHORTAGE OF MATERIAL, EQUIPMENT OR TRANSPORT, ANY LAW, REGULATION, OR ANY RULING OF COURT, TRIBUNAL OR GOVERNMENTAL AGENCY.</p>
            <h1 id="limitation-of-liability">LIMITATION OF LIABILITY</h1>
            <p>WITHOUT DEROGATING FROM THE FOREGOING, IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ADAO STAKING PORTAL, AND/OR ANY OF ADAO STAKING PORTAL PARTIES, BE LIABLE TO YOU FOR ANY DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE CONTENT AND/OR THE ADAO STAKING PORTAL NETWORK / SOFTWARE (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE SOFTWARE TO OPERATE WITH ANY OTHER SOFTWARE) EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR CERTAIN TYPES OF DAMAGES, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. IN SUCH JURISDICTIONS, ADAO STAKING PORTAL&#39;S LIABILITY IS LIMITED AND WARRANTIES ARE EXCLUDED TO THE GREATEST EXTENT PERMITTED BY THE CORRESPONDING APPLICABLE LAW. ADDITIONALLY, YOU ACKNOWLEDGE THAT NEITHER ADAO STAKING PORTAL NOR ANY ADAO STAKING PORTAL PARTIES DOES NOT ACTS OR SERVES AS YOUR BROKER, INTERMEDIARY, AGENT, OR ADVISOR WITH RESPECT TO ANY ACTION (INCLUDING REFRAINING FROM ANY ACTION), INCLUDING WITHOUT LIMITATION, ANY CONVERSION, YOU MAKE OR PROPOSE TO MAKE USING THE CONTENT AND OWES YOU NO FIDUCIARY DUTY.</p>
            <h2 id="computer-viruses">Computer Viruses</h2>
            <p>You acknowledge and agree that ADAO and its affiliates bear no liability for any interruptions or damage caused by any computer viruses, worms, spyware, scareware, Trojan horses, defects, corrupted files, hoaxes, or other malware that may affect your computer or other equipment, or any phishing, spoofing or other attack. You should also be aware that SMS and email services are vulnerable to spoofing and phishing attacks and should use care in reviewing messages purporting to originate from us. We advise the regular use of a reputable and readily available virus screening and prevention software.</p>
            <h2 id="miscellaneous">Miscellaneous</h2>
            <ul>
                <li>The controlling language for these terms of use is English; the meaning of terms, conditions and representations herein are subject to definitions and interpretations in the English language. Any translation is provided for your convenience and may not be deemed to represent accurately the information in the original English.</li>
                <li>If any provision of these Terms is determined to be invalid or unenforceable, the provision shall be deemed to be severable from the remainder of these Terms and will not cause their invalidity or unenforceability.</li>
                <li>These terms of use may be amended from time to time. It is your responsibility to check these terms of use periodically for changes. Your continued use of the software following the posting of changes will mean that you accept and agree to the changes. If you do not agree with any such modification, you should not use the ADAO Staking Portal.</li>
            </ul>
            <h1 id="if-you-do-not-fully-accept-agree-to-all-terms-set-forth-above-please-do-not-proceed-to-access-or-engange-with-the-adao-staking-portal-protocol">IF YOU DO NOT FULLY ACCEPT AGREE TO ALL TERMS SET FORTH ABOVE, PLEASE DO NOT PROCEED TO ACCESS OR ENGANGE WITH THE ADAO STAKING PORTAL PROTOCOL</h1>
        </>
    )

}


export default TermsOfUse